#obj-m:= test_timer.o
#modules-objs:= test_timer.o

obj-m := hightimer.o
modules-objs:= hightimer.o

KDIR:= /usr/src/linux-headers-`uname -r`
PWD:= $(shell pwd)

default:
	make -C $(KDIR) M=$(PWD) modules
clean:
	rm -rf *.ko *.mod.c *.mod.o *.o *.markers *.symvers *.order

